/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void delay(void){
	for(uint32_t i=0 ; i<=300000 ; i++);
}

int main(void)
{
    // Peripheral Registers Addresses
    uint32_t volatile *const pGPIOModeReg   = (uint32_t*)(0x40020C00);
    uint32_t volatile *const pOutputDataReg = (uint32_t*)(0x40020C00 + 0x10);
    uint32_t volatile *const pInputDataReg  = (uint32_t*)(0x40020C00 + 0x14);
    uint32_t volatile *const pClkCtrlReg    = (uint32_t*)(0x40023800 + 0x30);
    uint32_t volatile *const pPullupDownReg = (uint32_t*)(0x40020C00 + 0x0C);

    // Step 1: Enabling the Peripheral GPIO Clock
    *pClkCtrlReg |= (1 << 3);

    // Step 2: Configuring PD0, PD1, PD2, PD3 as output (rows)
    *pGPIOModeReg &= ~(0xFF); // Clearing of Bits
    *pGPIOModeReg |= 0x55;    // Setting of pins

    // Step 3: Configuring PD8, PD9, PD10, PD11 as Input (Column)
    *pGPIOModeReg &= ~(0xFF << 16);

    // Step 4: Enabling Pull-up Registers for PD8, PD9, PD10, PD11 as Input (Column)
    *pPullupDownReg &= ~(0xFF << 16);
    *pPullupDownReg |= (0x55 << 16);

    while (1){
    	//Step 5: Make all rows as High of
		*pOutputDataReg |= 0x0F;
		*pOutputDataReg &= ~(1 << 0);			    //Make R1 Low PD0

		//Check C1(PD8) low or high
		if(!(*pInputDataReg & (1 << 8))){
			//Key is Pressed
			printf("1/n");
		}
		delay();
		//Check C2(PD9) low or high
		if(!(*pInputDataReg & (1 << 9))){
			//Key is Pressed
			printf("2/n");
		}
		delay();
		//Check C3(PD10) low or high
		if(!(*pInputDataReg & (1 << 10))){
			//Key is Pressed
			printf("3/n");
		 }
		delay();
		//Check C4(PD11) low or high

		if(!(*pInputDataReg & (1 << 11))){
			//Key is Pressed
			printf("A/n");
		}
		delay();
		//Make All rows as High
		*pOutputDataReg |= 0x0f;
		*pOutputDataReg &= ~(1 << 1); 			//Make R2 Low PD1

		//Check C1(PD8) low or high
		if(!(*pInputDataReg & (1 << 8))){
			//Key is Pressed
			printf("4/n");
		}
		delay();
		//Check C2(PD9) low or high
		if(!(*pInputDataReg & (1 << 9))){
			//Key is Pressed
			printf("5/n");
		}
		delay();
		//Check C3(PD10) low or high
		if(!(*pInputDataReg & (1 << 10))){
		 //Key is Pressed
			printf("6/n");
		 }
		 delay();
		 //Check C4(PD11) low or high

		 if(!(*pInputDataReg & (1 << 11))){
		   //Key is Pressed
			 printf("B/n");
		 }
		 delay();
		 //Make All rows as High
		*pOutputDataReg |= 0x0f;
		*pOutputDataReg &= ~(1 << 2);			//Make R3 Low PD2

		//Check C1(PD8) low or high
		if(!(*pInputDataReg & (1 << 8))){
			//Key is Pressed
			printf("7/n");
		}
		delay();
		//Check C2(PD9) low or high
		if(!(*pInputDataReg & (1 << 9))){
			//Key is Pressed
			printf("8/n");
		}
		delay();
		//Check C3(PD10) low or high
		if(!(*pInputDataReg & (1 << 10))){
		 //Key is Pressed
			printf("9/n");
		 }
		 delay();
		 //Check C4(PD11) low or high

		 if(!(*pInputDataReg & (1 << 11))){
		   //Key is Pressed
			 printf("C/n");
		 }
		 delay();
		 //Make All rows as High
		*pOutputDataReg |= 0x0f;
		*pOutputDataReg &= ~(1 << 3);			//Make R4 Low PD3

		//Check C1(PD8) low or high
		if(!(*pInputDataReg & (1 << 8))){
			//Key is Pressed
			printf("*/n");
		}
		delay();
		//Check C2(PD9) low or high
		if(!(*pInputDataReg & (1 << 9))){
			//Key is Pressed
			printf("0/n");
		}
		delay();
		//Check C3(PD10) low or high
		if(!(*pInputDataReg & (1 << 10))){
		 //Key is Pressed
			printf("#/n");
		 }
		 delay();
		 //Check C4(PD11) low or high

		 if(!(*pInputDataReg & (1 << 11))){
		   //Key is Pressed
			 printf("D/n");
		 }
		 delay();
    } //While end

}
